// <auto-generated />
using Fiszki.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fiszki.Migrations
{
    [DbContext(typeof(WordListContext))]
    partial class WordListContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Fiszki.Models.Word", b =>
                {
                    b.Property<int>("IdWord")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("EnglishVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PolishVersion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdWord");

                    b.ToTable("Word");
                });
#pragma warning restore 612, 618
        }
    }
}
